services:
  - type: web
    name: fxop-md
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_ID
        generateValue: true
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile

databases:
  - name: fxop-md
    plan: free